<?php
/**
 * Copyright © Qoliber. All rights reserved.
 *
 * @category    Qoliber
 * @package     Qoliber_ProductPack
 * @author      Jakub Winkler <jwinkler@qoliber.com>
 * @author      Wojciech M. Wnuk <wwnuk@qoliber.com>
 * @author      Łukasz Owczarczuk <lowczarczuk@qoliber.com>
 */

use Qoliber\ProductPack\Model\Product\Type\Pack as PackType;
use Qoliber\ProductPack\ViewModel\Product\Pack;
use Magento\Framework\View\Element\Template;
use Magento\Quote\Model\Quote\Item;

/** @var Template $block */
/** @var Pack $viewModel */
/** @var Item $item */
$item = $block->getParentBlock()->getData('item');
?>
<?php if ($item->getProduct()->getTypeId() === PackType::TYPE_CODE): ?>
    <?php
        $viewModel = $block->getData('viewModel');
        $buyRequest = $item->getBuyRequest();
        $packOption = $buyRequest->getData('pack_option');

        // check null param for multi cart data
        if ($packOption === null) {
            $itemOptions = $viewModel->getProductItemOptions((int)$item->getId());
            foreach ($itemOptions as $itemOption) {
                if ($itemOption->getCode() === "info_buyRequest") {
                    $buyRequest = json_decode($itemOption->getValue(), true);
                    if ($buyRequest) {
                        $packOption = $buyRequest['pack_option'] ?? null;
                    }
                }
            }
        }
        
        $title = $packOption['title'] ?? '';
        $qty = $packOption['pack_size'] ?? '';
    ?>
    <?php if ((int)$qty > 1): ?>
        <div class="pack-options-container">
            <div class="pack-option-title">
                <span><?= __('Package') ?>:&nbsp;<strong><?= __($title) ?></strong></span>
            </div>
            <div class="pack-option-qty">
                <span><?= __('Units') ?>:&nbsp;</span><strong><?= $qty
                    ?></strong>
            </div>
        </div>
    <?php endif ?>
<?php endif; ?>
